# Generated by Django 5.2.1 on 2026-10-06 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insumo',
            new_name='Ingrediente',
        ),
        migrations.CreateModel(
            name='ProdutoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Quantidade usada na receita', max_digits=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.ingrediente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='ingredientes',
            field=models.ManyToManyField(through='calculadora.ProdutoIngrediente', to='calculadora.ingrediente'),
        ),
    ]
