# Generated by Django 5.2.1 on 2026-10-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_rename_insumo_ingrediente_produtoingrediente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoingrediente',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ingredientes',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='margem_lucro_percentual',
        ),
        migrations.RemoveField(
            model_name='produtoingrediente',
            name='produto',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(max_length=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='calculadora.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produtoingrediente',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='calculadora.item'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('margem_lucro_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('itens', models.ManyToManyField(through='calculadora.ProdutoIngrediente', to='calculadora.item')),
            ],
        ),
        migrations.AddField(
            model_name='produtoingrediente',
            name='prato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calculadora.prato'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
    ]
