# Generated by Django 5.2.1 on 2026-10-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_remove_produtoingrediente_ingrediente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prato',
            name='margem_lucro_percentual',
        ),
        migrations.AddField(
            model_name='item',
            name='quantidadeCompra',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Quantidade comprada do prato', max_digits=10),
            preserve_default=False,
        ),
    ]
