# Generated by Django 5.2.1 on 2026-10-07 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0004_remove_prato_margem_lucro_percentual_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutoIngrediente',
            new_name='PratoItem',
        ),
    ]
