# Generated by Django 5.2.1 on 2026-10-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0005_rename_produtoingrediente_pratoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantidadeCompra',
            new_name='quantidade_compra',
        ),
    ]
